#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Cloning PG Blitz - From Installer
      git:
        repo: 'https://github.com/vFlagR/PGBlitz.com'
        dest: /opt/plexguide
        version: 'gce_no_nvme'
        force: yes
